# Generated by Django 4.2.1 on 2025-10-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
